"""Remove analysis_type from models

Revision ID: e58483348f55
Revises: 
Create Date: 2025-10-28 20:50:38.505414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58483348f55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_tasks_analysis_type')
        batch_op.drop_column('analysis_type')

    with op.batch_alter_table('analyzer_configurations', schema=None) as batch_op:
        batch_op.drop_index('ix_analyzer_configurations_analyzer_type')
        batch_op.drop_column('analyzer_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyzer_type', sa.VARCHAR(length=17), nullable=False))
        batch_op.create_index('ix_analyzer_configurations_analyzer_type', ['analyzer_type'], unique=False)

    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_type', sa.VARCHAR(length=17), nullable=False))
        batch_op.create_index('ix_analysis_tasks_analysis_type', ['analysis_type'], unique=False)

    # ### end Alembic commands ###
