"""Add comprehensive security tool configuration fields

Revision ID: 44361c0e780d
Revises: 19355bb85378
Create Date: 2025-08-12 12:49:29.076715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44361c0e780d'
down_revision = '19355bb85378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bandit_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('safety_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pylint_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('eslint_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('npm_audit_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('snyk_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zap_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('zap_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('semgrep_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('semgrep_config_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('severity_threshold', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_issues_per_tool', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timeout_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exclude_patterns', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('include_patterns', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tools_run_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tools_failed_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('global_config_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_analyses', schema=None) as batch_op:
        batch_op.drop_column('global_config_json')
        batch_op.drop_column('tools_failed_count')
        batch_op.drop_column('tools_run_count')
        batch_op.drop_column('include_patterns')
        batch_op.drop_column('exclude_patterns')
        batch_op.drop_column('timeout_minutes')
        batch_op.drop_column('max_issues_per_tool')
        batch_op.drop_column('severity_threshold')
        batch_op.drop_column('semgrep_config_json')
        batch_op.drop_column('semgrep_enabled')
        batch_op.drop_column('zap_config_json')
        batch_op.drop_column('zap_enabled')
        batch_op.drop_column('snyk_config_json')
        batch_op.drop_column('npm_audit_config_json')
        batch_op.drop_column('eslint_config_json')
        batch_op.drop_column('pylint_config_json')
        batch_op.drop_column('safety_config_json')
        batch_op.drop_column('bandit_config_json')
        batch_op.drop_column('description')
        batch_op.drop_column('analysis_name')

    # ### end Alembic commands ###
